controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
    
    rear_steer_position_controller:
      type: position_controllers/JointGroupPositionController


ackermann_steering_controller:
  ros__parameters:

    rear_wheels_names: ["propulsion_1_joint", "propulsion_2_joint"]
    
    front_wheels_names: ["steer_1_joint", "steer_2_joint"]
    
    front_wheel_track: 0.6604
    rear_wheel_track: 0.6604
    wheelbase: 0.8382
    front_wheels_radius: 0.254
    rear_wheels_radius: 0.254
    use_stamped_vel: true


rear_steer_position_controller:
  ros__parameters:
    joints:
      - steer_3_joint
      - steer_4_joint
    interface_name: position
